---
crd:
  - name: external-snapshotter
    enabled: true
    path: ./client/config/crd
    tag: v8.2.1
    url: https://github.com/kubernetes-csi/external-snapshotter.git
  - name: prometheus-operator
    enabled: true
    path: .
    tag: v0.83.0
    url: https://github.com/prometheus-operator/prometheus-operator.git
