---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-gateway-api
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: traefik-gateway-api
  timeout: 15m0s
  dependsOn:
    - name: flux
      namespace: sre
  chart:
    spec:
      interval: 5m
      chart: gwapi
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: sre
  install:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    crds: CreateReplace
  # TODO: images
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: ""
  #           newName: ""
  #           newTag: ""
  values:
    envoy:
      enabled: false
    traefik:
      enabled: true
      experimental:
        knative: true
      gatewayClass:
        enabled: true
        # name: traefik
      providers:
        kubernetesGateway:
          enabled: true
          experimentalChannel: false
        knative:
          enabled: true
